
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kyleq
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    private String databaseUrl = "jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private String username = "root";
    private String password = "";
    private HotelDatabaseManager hotelDBM = new HotelDatabaseManager(databaseUrl, username, password);
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        hotelLogo = new javax.swing.JLabel();
        uNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        fNameLabel = new javax.swing.JLabel();
        phoneNoLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        lnameTextField = new javax.swing.JTextField();
        unameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        loginHeaderLabel = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        confPasswordLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        confirmPasswordPasswordField = new javax.swing.JPasswordField();
        notifLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register - Payter Hotel");
        setPreferredSize(new java.awt.Dimension(872, 559));
        setResizable(false);
        setSize(new java.awt.Dimension(872, 559));

        logoPanel.setBackground(new java.awt.Color(196, 167, 111));
        logoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        hotelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hotel-logo.png"))); // NOI18N
        hotelLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hotelLogo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hotelLogo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(hotelLogo)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        uNameLabel.setText("Username:");

        emailLabel.setText("Email:");

        fnameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registerButton.setBackground(new java.awt.Color(80, 60, 19));
        registerButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        goBackButton.setBackground(new java.awt.Color(80, 60, 19));
        goBackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("Go Back");
        goBackButton.setBorderPainted(false);
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        fNameLabel.setText("First Name:");

        phoneNoLabel.setText("Phone #:");

        lNameLabel.setText("Last Name:");

        passLabel.setText("Password");

        lnameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        unameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loginHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginHeaderLabel.setText("REGISTER");

        passwordPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPasswordFieldActionPerformed(evt);
            }
        });

        confPasswordLabel.setText("Confirm Password:");

        emailTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        confirmPasswordPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        notifLabel.setForeground(new java.awt.Color(255, 51, 51));
        notifLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(confPasswordLabel)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNoLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(uNameLabel)
                                    .addComponent(lNameLabel)
                                    .addComponent(fNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(confirmPasswordPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(unameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(goBackButton)
                    .addComponent(loginHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(loginHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notifLabel)
                .addGap(63, 63, 63)
                .addComponent(goBackButton)
                .addGap(25, 25, 25))
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        registerButton.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void unameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTextFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String first_name = fnameTextField.getText().trim();
        String last_name = lnameTextField.getText().trim();
        String username = unameTextField.getText().trim();
        String email = emailTextField.getText().trim();
        String phone_number = phoneTextField.getText().trim();
        String password = String.valueOf(passwordPasswordField.getPassword());
        String confirm_password = String.valueOf(confirmPasswordPasswordField.getPassword());
        
        if(!first_name.isEmpty() && !last_name.isEmpty() && !username.isEmpty() && !email.isEmpty() && !phone_number.isEmpty() && !password.isEmpty() && !confirm_password.isEmpty()){
            if(!hotelDBM.isUsernameExist(username)){
                if(!hotelDBM.isEmailUsed(email)){
                    if(hotelDBM.registerUser(first_name, last_name, username, email, phone_number, password)){
                        if(password.equals(confirm_password)){
                            notifLabel.setText("User " + username + " successfully registered!");
                        }
                        else{
                            notifLabel.setText("Passwords do not match!");
                        }
                    }
                    else{
                        notifLabel.setText("Error occured");
                    }
                }
                else{
                    notifLabel.setText("Email already used!");
                }
            }
            else{
                notifLabel.setText("Username is already taken!");
            }
        }
        else{
            notifLabel.setText("All fields must be filled!");
        }
        
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void passwordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPasswordFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confPasswordLabel;
    private javax.swing.JPasswordField confirmPasswordPasswordField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel hotelLogo;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JLabel loginHeaderLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel notifLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel uNameLabel;
    private javax.swing.JTextField unameTextField;
    // End of variables declaration//GEN-END:variables
}
