/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author kyleq
 */
public class UserRequestService extends javax.swing.JDialog {

    /**
     * Creates new form RequestService
     */
    
    private String databaseUrl = "jdbc:mysql://localhost:3306/hotel?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private String username = "root";
    private String password = "";
    private HotelDatabaseManager hotelDBM = new HotelDatabaseManager(databaseUrl, username, password);
    
    private Guest guest = null;
    private User user = null;
    private int room_number;
    private int checkin_id;
    
    public UserRequestService(java.awt.Frame parent, boolean modal, Guest guest, User user, int room_number, int checkin_id) {
        super(parent, modal);
        this.guest=guest;
        this.user=user;
        this.room_number=room_number;
        this.checkin_id=checkin_id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        roomNumberLabel = new javax.swing.JLabel();
        roomNoLabel = new javax.swing.JLabel();
        chooseServiceLabel = new javax.swing.JLabel();
        serviceTypesComboBox = new javax.swing.JComboBox<>();
        notifLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        costLowerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Confirm Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        roomNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        roomNumberLabel.setText("Room Number:");

        chooseServiceLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        chooseServiceLabel.setText("Choose Service:");

        serviceTypesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"WIFI Access", "Laundry and Dry Cleaning", "Entertainment Services", "Snacks and Drinks", "Housekeeping"}));
        serviceTypesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                serviceTypesComboBoxItemStateChanged(evt);
            }
        });

        notifLabel.setForeground(new java.awt.Color(255, 102, 102));
        notifLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        costLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        costLabel.setText("Cost:");

        costLowerLabel.setText("₱250.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notifLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseServiceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serviceTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(costLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costLowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumberLabel)
                    .addComponent(roomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseServiceLabel)
                    .addComponent(serviceTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(costLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(costLowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        roomNoLabel.setText(String.valueOf(room_number));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int service_id = 0;
        
        if("WIFI Access".equals(serviceTypesComboBox.getSelectedItem().toString())){
            service_id=1;
        }
        else if("Laundry and Dry Cleaning".equals(serviceTypesComboBox.getSelectedItem().toString())){
            service_id=2;
        }
        else if("Entertainment Services".equals(serviceTypesComboBox.getSelectedItem().toString())){
            service_id=3;
        }
        else if("Snacks and Drinks".equals(serviceTypesComboBox.getSelectedItem().toString())){
            service_id=4;
        }
        else if("Housekeeping".equals(serviceTypesComboBox.getSelectedItem().toString())){
            service_id=5;
        }
        
        if(hotelDBM.isServiceRequested(service_id, checkin_id)){
            notifLabel.setText("You already submitted a request for this service!");
        }
        else{
            if(hotelDBM.registerRequestService(service_id, checkin_id)){
                notifLabel.setText("Request submitted!");
            }
            else{
                notifLabel.setText("Error requesting a service!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void serviceTypesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_serviceTypesComboBoxItemStateChanged
        if("WIFI Access".equals(serviceTypesComboBox.getSelectedItem().toString())){
            costLowerLabel.setText("₱250.00");
        }
        else if("Laundry and Dry Cleaning".equals(serviceTypesComboBox.getSelectedItem().toString())){
            costLowerLabel.setText("₱150.00");
        }
        else if("Entertainment Services".equals(serviceTypesComboBox.getSelectedItem().toString())){
            costLowerLabel.setText("₱200.00");
        }
        else if("Snacks and Drinks".equals(serviceTypesComboBox.getSelectedItem().toString())){
            costLowerLabel.setText("₱100.00");
        }
        else if("Housekeeping".equals(serviceTypesComboBox.getSelectedItem().toString())){
            costLowerLabel.setText("₱300.00");
        }
    }//GEN-LAST:event_serviceTypesComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseServiceLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel costLowerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel notifLabel;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JComboBox<String> serviceTypesComboBox;
    // End of variables declaration//GEN-END:variables
}
